config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in:["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true
  validates :content, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end


  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new # needed to instantiate the form_for
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    # params[:restaurant]
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
    # Will raise ActiveModel::ForbiddenAttributesError
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end




# # read one
# def show
#   @task = Task.find(params[:id])
# end

# # create : GET the task creation
# def new
#   @task = Task.new # needed to instantiate the form_for
# end

# # create : POST the form
# def create
#   @task = Task.new(params[:task])
#   @task.save
#   # Will raise ActiveModel::ForbiddenAttributesError
#   redirect_to(@task.id)
# end

# # update in 2 steps
# def edit
#   @task = Task.find(params[:id])
# end

# def update
#   @task = Task.find(params[:id])
#   @task.update(params[:task])
#   @task.save
#   # Will raise ActiveModel::ForbiddenAttributesError
#   redirect_to task_path(@task)
# end

# def destroy
#   @task = Task.find(params[:id])
#   @task.destroy

#   render :index
#   redirect_to task_path(@task)

#   # no need for app/views/restaurants/destroy.html.erb
#   # redirect_to task_path(@task.id)
# end

# private

# def task_params
#   params.require(:task).permit(:title, :details, :completed)
# end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def commentary
    @reviews = Review.find(params[:restaurant_id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

<%= link_to 'new restaurant', new_restaurant_path %>
<%# <%= link_to new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

<%= link_to 'show', restaurant_path %>


<%# <%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%# <%= f.input :content %>
  <%# <%= f.submit "Submit review", class: "btn btn-primary" %>
<%# <% end % %>

<%# <% link_to %>

app/views/restaurants/show.html.erb
<h2> <%= @restaurant.name %> </h2>
<p> <%=@restaurant.address %> </p>
<p> <%=@restaurant.category %> </p>
<% @restaurant.reviews.each do |review| %>
  <p><%= review.rating%></p>
  <p><%= review.content%></p>
<% end %>


    <%# <%= link_to "Delete #{@restaurant.name}",  %>
        <%# restaurant_path(@restaurant),  %>
        <%# method: :delete,  %>
        <%# data: {conforme: "are you sure you want to delete ?"} %>

<%= link_to "list of restaurants", restaurants_path(@restaurant) %>
<%= link_to "let a review", new_restaurant_review_path(@restaurant) %>


<%# <%= link_to 'edit', edit_restaurant_path(@restaurant) %>
<%# <%= link_to 'Back', restaurants_path %>
<%# <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<%# <%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%# <%= f.input :content %>
  <%# <%= f.submit "Submit review", class: "btn btn-primary" %>
<%# <% end % %>


<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit%>
<% end %>

<%= link_to 'index', restaurants_path %>